### ISSUE TITLE
Implement EVALSHA command

### ISSUE THREAD

**Issue by fredmajor** [stipsan/ioredis-mock#1097]
I am currently trying to use ioredis-mock together with [node-redlock](https://github.com/mike-marcacci/node-redlock/tree/v4.2.0) but unfortunately it results in:
```
Unsupported command: "evalsha", please check the full list over mocked commands: https://github.com/stipsan/ioredis-mock/blob/master/compat.md#supported-commands-
TypeError: Unsupported command: "evalsha", please check the full list over mocked commands: https://github.com/stipsan/ioredis-mock/blob/master/compat.md#supported-commands-
    at RedisMock.value (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/ioredis-mock/jest.js:11624:19)
    at Redlock.Object.<anonymous>.Redlock._executeScript (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/redlock.js:455:16)
    at request (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/redlock.js:369:17)
    at /Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/redlock.js:436:12
    at Array.forEach (<anonymous>)
    at attempt (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/redlock.js:435:24)
    at /Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/redlock.js:440:10
    at Promise._execute (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/node_modules/bluebird/js/release/promise.js:103:10)
    at Redlock._lock (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/redlock.js:359:9)
    at Redlock.lock (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/redlock/redlock.js:180:14)
    at AttemptSessionService.updateAttemptSession (/Users/fred/w/_portal/Lms.Event.Processor/src/attempt-session/attempt-session.service.ts:38:35)
    at Object.<anonymous> (/Users/fred/w/_portal/Lms.Event.Processor/src/attempt-session/attempt-session.service.spec.ts:110:36)
    at Promise.then.completed (/Users/fred/w/_portal/Lms.Event.Processor/node_modules/jest-circus/build/utils.js:390:28)
    at new Promise (<anonymous>)
```
so definitely evalsha is needed here. 

I am happy to take a stab at this myself, only please someone provide me with some clues, as I am not familiar with internal project's architecture. I guess the script's hash and contents should be first stored somewhere upon calling EVAL, and later invoked by the new EVALSHA.

**Comment by stipsan** [comment]
You're welcome to have a jab at it 👍  I can't help you much though on the implementation as I have no experience using Lua myself, it's entirely contributed by the community 😅

**Comment by fredmajor** [comment]
@stipsan I already produced a beta version but will hold on from opening a PR until I confirm it actually does everything it should (at least for my current project). Expect a PR coming next week :)
