### ISSUE TITLE
hexists fails

### ISSUE THREAD

**Issue by wraytw** [stipsan/ioredis-mock#330]
When using hexists with 'ioredis', it works great!

However, using hexists with 'ioredis-mock' throws an error. Below is my usage, and the error being thrown

My environment:
`node version: 6.9.4`
`npm version: 4.4.1`

```javascript
let redis = new RedisMock()
let exists = redis.hexists('thing.bob', 'session')
```

That call to hexists throws an error: 
```error
TypeError: Cannot convert undefined or null to object
      at hasOwnProperty (<anonymous>)
      at RedisMock.hexists (node_modules/ioredis-mock/lib/commands/hexists.js:8:28)
      at node_modules/ioredis-mock/lib/command.js:38:30
      at Promise._execute (node_modules/ioredis-mock/node_modules/bluebird/js/release/debuggability.js:300:9)
      at Promise._resolveFromExecutor (node_modules/ioredis-mock/node_modules/bluebird/js/release/promise.js:483:18)
      at new Promise (node_modules/ioredis-mock/node_modules/bluebird/js/release/promise.js:79:10)
      at RedisMock.hexists (node_modules/ioredis-mock/lib/command.js:37:12)
      at src/services/session.js:96:32
      at next (native)
      at undefined.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at node_modules/bluebird/js/release/generators.js:201:15
      at hasSession (src/services/session.js:93:28)
      at Context.<anonymous> (test/services/session.test.js:15:40)
      at next (native)
      at undefined.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Context.<anonymous> (node_modules/bluebird/js/release/generators.js:201:15)
```

Maybe I'm missing something, if so please let me know.

But as soon as I switch to using ioredis instead of ioredis-mock, the code works. 

Thanks

EDIT: I have a pull request ready for this issue. I'll attach it to this issue shortly

**Comment by wraytw** [comment]
I've created a pull request for this issue

#331

**Comment by stipsan** [comment]
Closing this as the PR is merged and released 🙂

**Comment by stipsan** [comment]
Closing this as the PR is merged and released 🙂
