### ISSUE TITLE
Custom commands don't work with multi/pipeline

### ISSUE THREAD

**Issue by mishan** [stipsan/ioredis-mock#878]
Redis custom commands don't work with multi/pipeline in ioredis-mock, but they are supported in ioredis (see https://github.com/luin/ioredis/blob/master/test/functional/pipeline.ts#L184)

```
TypeError: Cannot read property 'apply' of undefined
    at ioredis-mock/lib/index.js:118:49
    at Array.forEach (<anonymous>)
    at RedisMock.multi (ioredis-mock/lib/index.js:111:13)
    at Object.<anonymous> (test-redis.js:10:7)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
```

Example script:
```
const IORedisMock = require('ioredis-mock');
const redis = new IORedisMock();

redis.defineCommand('test', {
  numberOfKeys: 1,
  lua: "return {unpack(KEYS),unpack(ARGV)}"
});

redis.multi(['test', 'a', 1]).exec();
```

**Comment by TysonAndre** [comment]
The issues seem to be in src/pipeline.js and src/commands/defineCommand.js. One solution would be to maintain a separate set such as this._customCommands

```js
// src/commands/defineCommand.js
export function defineCommand(command, { numberOfKeys, lua: luaCode }) {
  this[command] = createCommand(
    customCommand(numberOfKeys, luaCode).bind(this),
    command,
    this
  );
  // Add this._customCommands for Pipeline to check?
}
```

```js
src/pipeline.js
class Pipeline {
  constructor(redis) {
    this.batch = [];
    this.redis = redis;
    this._transactions = 0;

    Object.keys(commands).forEach(command => {
      this[command] = this._createCommand(command);
    });
    // Also iterate over redis._customCommands?
  }
```
